#!/usr/bin/env bash

TAG=r.example-renv
TARGET=renv
#HOST_PATH=$(pwd) # try to write clean lockfile to host filesystem later.
#GUEST_PATH=/app/

docker build \
  --tag $TAG \
  --target=$TARGET \
  --file Dockerfile \
  .

docker run \
    --rm \
    $TAG \
    ls -a \
    && Rscript -e "renv::status()" \
    && Rscript -e "renv::snapshot()"