#!/usr/bin/env bash

TAG=r.example-test
TARGET=with-packages

docker build \
  --tag $TAG \
  --target=$TARGET \
  --file Dockerfile \
  .

docker run \
    --rm \
    $TAG \
    R -e "devtools::check()"
